### ISSUE TITLE
how to get token

### ISSUE THREAD

**Issue by ZhiwenDeng-dev** [BlackPhoenix134/MidjourneyAutomation#1]
hi,bro,can you tell me how to get BOT_TOKEN and relay token? thanks

**Comment by BlackPhoenix134** [comment]
Hi
The bot token is the token of your bot that you have to create and invite on your server.
https://discord.com/developers/applications
Create an application, add a bot, give it the proper rights (I gave it all text permission, or give it all rights). In case you looked your channels behind a role, your bot also needs this role. Be sure to save your bot token on creation, it can only be viewed once. If you forgot it you have to reset it.
https://www.androidauthority.com/get-discord-token-3149920/
There you can also find a tutorial on how to get the account token where you have an active subscription, that's the user that is used to make the requests

**Comment by ZhiwenDeng-dev** [comment]
thanks a lot! bro
root@cloud01:~/tool/MidjourneyAutomation# python3.10 main.py
 * Serving Flask app 'flaskclient'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8089
 * Running on http://155.138.253.17:8089
Press CTRL+C to quit
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1191, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/usr/local/lib/python3.10/dist-packages/werkzeug/serving.py", line 1069, in run_simple
    srv.serve_forever()
  File "/usr/local/lib/python3.10/dist-packages/werkzeug/serving.py", line 766, in serve_forever
    super().serve_forever(poll_interval=poll_interval)
  File "/usr/lib/python3.10/socketserver.py", line 232, in serve_forever
    ready = selector.select(poll_interval)
  File "/usr/lib/python3.10/selectors.py", line 419, in select
    for fd, event in fd_event_list:
  File "/usr/lib/python3.10/selectors.py", line 419, in select
    for fd, event in fd_event_list:
  File "/root/tool/MidjourneyAutomation/flaskclient.py", line 23, in tracer
    raise StopThread()
flaskclient.StopThread

**Comment by ZhiwenDeng-dev** [comment]
When I generated the robot token and passed in RELAY_TOKEN, I tried to pass in the "authorization" of discord and the above error was thrown. After the error, I tried to log in to midjourney's webpage and passed in midjourney's "__Secure- next-auth.session-token" still throws the above error, what is wrong with me, can you give an example?

**Comment by BlackPhoenix134** [comment]
I should write a better readme when I have more time.
Your .env file should look like this
BOT_TOKEN = "..."
RELAY_TOKEN = "..."
Moreover, both, you and your bot have to be in the same server you want to use it from.
You also have to change the channel ids you want to use for the bot in mjbot.py

Ours look like this
```
channel_id_protocol = 1077698060085383188
channel_id_upscaled = 1077582970547871784

channel_bot_1 = 1077519680136294472
channel_bot_2 = 1077568863316746272
channel_bot_3 = 1077580957915287582
```
Protocol channel is one that you can input /commands to, and is also used to log some data
the upscaled channel contains the upscaled images

Are you sure you inserted YOUR discord token in relay token, and the correct bot token (the secret you see when creating it) in the bot token field?

**Comment by BlackPhoenix134** [comment]
I accidentally close your issue. But you can also write me on discord, link is on my website. I can help you better there

**Comment by ZhiwenDeng-dev** [comment]
hi, bro, thank you very much for your answer, because I am relatively new to discord development,,, I want to know how to contact you, where is your discord link, I need your help

**Comment by BlackPhoenix134** [comment]
https://discord.com/users/338617792653819915
